/* Orbit: look definitions (shared, dependency-free)
 *
 * The single source of truth for the available looks. It is plain data with no
 * imports, so the WebGPU engine, the scene schema, the demo UI and the landing
 * page can all read it without pulling in a renderer.
 *
 * `params` are numeric shader knobs, `colors` are shared palette entries, and
 * `swatch` / `ui` drive the lens picker and the interface theme.
 */

/**
 * The available looks, in weight-uniform order.
 * `params` are numeric shader knobs, `colors` are shared palette entries.
 */
export const LOOKS = [
  {
    id: 'realistic',
    label: 'Realistic',
    blurb: 'Rayleigh atmosphere, living clouds, ocean glint, city lights',
    swatch: ['#06224f', '#3c7a3a', '#dfe9f7'],
    ui: { accent: '#5ad1ff', paper: false },
    params: {
      bloomStrength: 0.5,
      bloomRadius: 0.6,
      bloomThreshold: 0.8,
      exposure: 1.0,
      tonemap: 1.0,
      vignette: 0.4,
      grain: 0.03,
      chroma: 0.0005,
      atmos: 1.0,
      beamWidth: 0.0062,
      beamGlow: 1.0,
      starBright: 1.0,
      cloudAlpha: 1.0,
      sparkSize: 0.011,
      moteSize: 0.0034,
      moteGlow: 0.32,
      auroraAmt: 1.0,
    },
    colors: { bgA: '#01020a', bgB: '#040716', accent: '#5ad1ff', rim: '#6fb4ff' },
  },
  {
    id: 'cartoon',
    label: 'Cartoon',
    blurb: 'Toon shading, bold outlines, puffy flat clouds',
    swatch: ['#2f8bff', '#5bd35b', '#ffd84a'],
    ui: { accent: '#ffb02e', paper: false },
    params: {
      bloomStrength: 0.12,
      bloomRadius: 0.3,
      bloomThreshold: 0.95,
      exposure: 1.0,
      tonemap: 0.3,
      vignette: 0.12,
      grain: 0.0,
      chroma: 0.0,
      atmos: 1.0,
      beamWidth: 0.0105,
      beamGlow: 0.35,
      starBright: 1.0,
      cloudAlpha: 1.0,
      sparkSize: 0.03,
      moteSize: 0.008,
      moteGlow: 0.3,
      auroraAmt: 0.5,
    },
    colors: { bgA: '#2b2a6e', bgB: '#4a2f8f', accent: '#ffd84a', rim: '#9fd8ff' },
  },
  {
    id: 'neon',
    label: 'Neon',
    blurb: 'Synthwave grid, glowing coastlines, heavy bloom',
    swatch: ['#16002b', '#ff2fb3', '#25f4ee'],
    ui: { accent: '#ff2fb3', paper: false },
    params: {
      bloomStrength: 0.7,
      bloomRadius: 0.55,
      bloomThreshold: 0.6,
      exposure: 1.05,
      tonemap: 0.75,
      vignette: 0.5,
      grain: 0.02,
      chroma: 0.0018,
      atmos: 0.9,
      beamWidth: 0.0058,
      beamGlow: 0.75,
      starBright: 0.6,
      cloudAlpha: 0.0,
      sparkSize: 0.012,
      moteSize: 0.0045,
      moteGlow: 0.3,
      auroraAmt: 1.0,
    },
    colors: { bgA: '#05000d', bgB: '#10032a', accent: '#25f4ee', rim: '#ff2fb3' },
  },
  {
    id: 'hologram',
    label: 'Hologram',
    blurb: 'Dot-matrix land, scanlines, chromatic fringe',
    swatch: ['#021a24', '#37e6ff', '#c9fbff'],
    ui: { accent: '#37e6ff', paper: false },
    params: {
      bloomStrength: 0.85,
      bloomRadius: 0.5,
      bloomThreshold: 0.45,
      exposure: 1.0,
      tonemap: 0.6,
      vignette: 0.55,
      grain: 0.05,
      chroma: 0.0028,
      atmos: 0.8,
      beamWidth: 0.0052,
      beamGlow: 1.3,
      starBright: 0.35,
      cloudAlpha: 0.0,
      sparkSize: 0.009,
      moteSize: 0.0035,
      moteGlow: 0.3,
      auroraAmt: 0.7,
    },
    colors: { bgA: '#010a10', bgB: '#02202c', accent: '#37e6ff', rim: '#37e6ff' },
  },
  {
    id: 'ink',
    label: 'Ink & Paper',
    blurb: 'Etched hatching on warm paper with one vermilion accent',
    swatch: ['#f1e8d4', '#1b1712', '#d8402a'],
    ui: { accent: '#d8402a', paper: true },
    params: {
      bloomStrength: 0.0,
      bloomRadius: 0.2,
      bloomThreshold: 1.5,
      exposure: 1.0,
      tonemap: 0.0,
      vignette: 0.28,
      grain: 0.09,
      chroma: 0.0,
      atmos: 0.0,
      beamWidth: 0.0072,
      beamGlow: 0.0,
      starBright: 0.0,
      cloudAlpha: 0.0,
      sparkSize: 0.022,
      moteSize: 0.0,
      moteGlow: 0.0,
      auroraAmt: 0.0,
    },
    colors: { bgA: '#efe5cd', bgB: '#e3d6b8', accent: '#d8402a', rim: '#1b1712' },
  },
];

/** Look id → index (the weight-uniform slot). */
export const LOOK_INDEX = Object.fromEntries(LOOKS.map((l, i) => [l.id, i]));
